version: '3.8'

services:  

  mysql:
    image: mysql:8.0.22
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

volumes:
  mysql_data: